# Generated by Django 5.2.8 on 2025-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_App', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
