# Generated by Django 5.2.8 on 2025-12-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_App', '0005_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Contact_App.registration'),
            preserve_default=False,
        ),
    ]
